"use client"

import * as React from "react"
import { ChevronDown, Info } from "lucide-react"
import { useTheme } from "next-themes"
import type { AssetDetail } from "@/app/lib/borrow-detail"
import { formatCompactUsd } from "@/app/lib/borrow-sim"
import { resolveChartAccent, toRgba, type ThemeMode } from "@/app/lib/chart-colors"
import { Card } from "@/components/ui/card"
import { cn } from "@/lib/utils"

const MONTH_LABELS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

type Props = { detail: AssetDetail }

export function CashflowTrendCard({ detail }: Props) {
  const { cashflowTrend } = detail
  const [hover, setHover] = React.useState<number | null>(null)
  const { resolvedTheme } = useTheme()
  const theme: ThemeMode = resolvedTheme === "dark" ? "dark" : "light"

  const series = cashflowTrend.series
  const values = series.points.map((p) => p.v)
  const hasData = values.some((v) => v > 0)

  const activeIndex = hover ?? Math.max(0, values.length - 1 - 4)
  const activePoint = series.points[activeIndex]

  const accent = resolveChartAccent({
    theme,
    accentClassName: detail.hero.visual.textClass,
  })

  return (
    <Card className="border-border bg-surface-raised p-5 shadow-elev-1 sm:p-6">
      <div className="flex items-start justify-between gap-4">
        <div className="min-w-0">
          <div className="flex items-center gap-1.5 text-[10.5px] font-medium uppercase tracking-[0.06em] text-muted-foreground">
            <span>Cash flow</span>
            <Info className="h-3 w-3 opacity-70" aria-hidden />
          </div>
          <div className="mt-1.5 font-data text-[24px] font-medium tabular-nums text-foreground sm:text-[28px]">
            {cashflowTrend.totalLabel}
          </div>
          <p className="mt-1 text-[11.5px] text-muted-foreground">
            Revenue generated by {detail.hero.symbol} — interest paid by borrowers over the last 12 months.
          </p>
        </div>
        <button
          type="button"
          className="inline-flex h-7 items-center gap-1.5 rounded-xs border border-border bg-surface-raised px-2.5 text-[12px] font-medium text-foreground transition-colors hover:bg-surface-inset"
        >
          {cashflowTrend.periodLabel}
          <ChevronDown className="h-3 w-3" aria-hidden />
        </button>
      </div>

      <div className="mt-5">
        {hasData ? (
          <BarChart
            values={values}
            activeIndex={activeIndex}
            onHoverIndex={setHover}
            accent={accent}
            activeLabel={formatMonthYear(activePoint.t)}
            activeValue={formatCompactUsd(activePoint.v)}
          />
        ) : (
          <div className="grid h-[220px] place-items-center text-sm text-muted-foreground">
            No revenue data available.
          </div>
        )}
      </div>
    </Card>
  )
}

type BarChartProps = {
  values: number[]
  activeIndex: number
  onHoverIndex: (i: number | null) => void
  accent: string
  activeLabel: string
  activeValue: string
}

function BarChart({ values, activeIndex, onHoverIndex, accent, activeLabel, activeValue }: BarChartProps) {
  const width = 720
  const height = 260
  const padTop = 56
  const padBottom = 32
  const padLeft = 36
  const padRight = 12
  const chartW = width - padLeft - padRight
  const chartH = height - padTop - padBottom

  const maxV = Math.max(...values, 1)
  const niceMax = niceCeil(maxV)
  const ticks = 4
  const gridVals = Array.from({ length: ticks }, (_, i) => (niceMax / (ticks - 1)) * i)

  const slot = chartW / values.length
  const barW = Math.min(28, slot * 0.5)
  const gradId = React.useId()
  const accentFaded = toRgba(accent, 0.85)
  const accentSoft = toRgba(accent, 0.6)

  const xForIndex = (i: number) => padLeft + slot * i + slot / 2 - barW / 2
  const yForValue = (v: number) => padTop + chartH - (v / niceMax) * chartH

  const activeX = xForIndex(activeIndex) + barW / 2

  const tooltipW = 150
  const tooltipH = 52
  const tooltipX = Math.min(width - tooltipW - 4, Math.max(4, activeX - tooltipW / 2))
  const tooltipY = Math.max(4, yForValue(values[activeIndex]) - tooltipH - 18)

  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      className="w-full select-none"
      preserveAspectRatio="none"
      onMouseLeave={() => onHoverIndex(null)}
      role="img"
      aria-label="Monthly revenue"
    >
      <defs>
        <linearGradient id={gradId} x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor={accentFaded} />
          <stop offset="100%" stopColor={accentSoft} />
        </linearGradient>
      </defs>

      {gridVals.map((v, i) => {
        const y = yForValue(v)
        return (
          <g key={i}>
            <line
              x1={padLeft}
              y1={y}
              x2={width - padRight}
              y2={y}
              stroke="currentColor"
              strokeOpacity={0.14}
              strokeDasharray="3 4"
              className="text-muted-foreground"
            />
            <text
              x={padLeft - 8}
              y={y + 3}
              textAnchor="end"
              className="fill-muted-foreground text-[10px]"
            >
              {formatAxisTick(v)}
            </text>
          </g>
        )
      })}

      {values.map((v, i) => {
        const x = xForIndex(i)
        const y = yForValue(v)
        const h = padTop + chartH - y
        const isActive = i === activeIndex
        return (
          <g key={i} onMouseEnter={() => onHoverIndex(i)}>
            <rect
              x={padLeft + slot * i}
              y={padTop}
              width={slot}
              height={chartH + padBottom}
              fill="transparent"
            />
            <rect
              x={x}
              y={y}
              width={barW}
              height={Math.max(2, h)}
              rx={barW / 2}
              ry={barW / 2}
              fill={isActive ? `url(#${gradId})` : "currentColor"}
              className={isActive ? undefined : "text-muted-foreground/25"}
            />
            <text
              x={x + barW / 2}
              y={height - padBottom / 2 + 4}
              textAnchor="middle"
              className={cn(
                "text-[11px] tabular-nums",
                isActive ? "fill-foreground font-medium" : "fill-muted-foreground",
              )}
            >
              {MONTH_LABELS[i % 12]}
            </text>
          </g>
        )
      })}

      <line
        x1={activeX}
        y1={yForValue(values[activeIndex])}
        x2={activeX}
        y2={padTop + chartH}
        stroke={accent}
        strokeOpacity={0.35}
        strokeDasharray="2 3"
      />
      <circle
        cx={activeX}
        cy={yForValue(values[activeIndex])}
        r={5}
        fill="white"
        stroke={accent}
        strokeWidth={2}
      />

      <g transform={`translate(${tooltipX}, ${tooltipY})`}>
        <rect
          width={tooltipW}
          height={tooltipH}
          rx={10}
          ry={10}
          className="fill-background stroke-border/60"
          strokeWidth={1}
          style={{ filter: "drop-shadow(0 4px 12px rgba(0,0,0,0.08))" }}
        />
        <text x={tooltipW / 2} y={20} textAnchor="middle" className="fill-muted-foreground text-[11px]">
          {activeLabel} :
        </text>
        <text
          x={tooltipW / 2}
          y={40}
          textAnchor="middle"
          className="fill-foreground text-[13px] font-medium tabular-nums"
        >
          {activeValue}
        </text>
      </g>
    </svg>
  )
}

function niceCeil(v: number): number {
  if (v <= 0) return 1
  const pow = 10 ** Math.floor(Math.log10(v))
  const n = v / pow
  const bucket = n <= 1 ? 1 : n <= 2 ? 2 : n <= 5 ? 5 : 10
  return bucket * pow
}

function formatAxisTick(v: number): string {
  if (v >= 1_000_000_000) return `${(v / 1_000_000_000).toFixed(0)}B`
  if (v >= 1_000_000) return `${(v / 1_000_000).toFixed(0)}M`
  if (v >= 1_000) return `${Math.round(v / 1_000)}k`
  return `${Math.round(v)}`
}

function formatMonthYear(iso: string): string {
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return iso
  return d.toLocaleDateString(undefined, { month: "long", year: "numeric" })
}
